<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function findUserByName($name)
    {
        return $this
            ->createQueryBuilder('user')
            ->where("user.name = :name")
            ->setParameter('category', $name)
            ->getQuery()
            ->getResult();
    }
}
